#ifndef SkTraceEventPhase_DEFINED
#  define SkTraceEventPhase_DEFINED
#  define TRACE_EVENT_PHASE_BEGIN	('B')
#  define TRACE_EVENT_PHASE_END	('E')
#  define TRACE_EVENT_PHASE_COMPLETE	('X')
#  define TRACE_EVENT_PHASE_INSTANT	('I')
#  define TRACE_EVENT_PHASE_ASYNC_BEGIN	('S')
#  define TRACE_EVENT_PHASE_ASYNC_END	('F')
#  define TRACE_EVENT_PHASE_COUNTER	('C')
#  define TRACE_EVENT_PHASE_CREATE_OBJECT	('N')
#  define TRACE_EVENT_PHASE_SNAPSHOT_OBJECT	('O')
#  define TRACE_EVENT_PHASE_DELETE_OBJECT	('D')
#endif
